### ISSUE TITLE
Missing sound level (exist in CPB)

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_BLE_BroadcastNet#13]
As identified in the example code for CPB, the library would be better with sound_level support:
https://github.com/adafruit/Adafruit_CircuitPython_BLE_BroadcastNet/blob/master/examples/ble_broadcastnet_cpb.py

**Comment by tekktrik** [comment]
Hi @dglaude!  I actually just submitted a PR to address this that's linked here if you want to check it out and potentially close the issue if it solves the problem!

**Comment by tekktrik** [comment]
PR is merged!  Please let me know if its sufficient to close the issue.

**Comment by dglaude** [comment]
Thank you, I totally forgot about this.
Testing this would require a big effort for me: Setting up a Pi, adding blinka and that test code, then catching my CPB and testing.

But the code is pretty simple so it feel good.

Thank you very much.

**Comment by tekktrik** [comment]
I don't have the hardware to test this so I'll so if anyone does (or I'll get some) so we can close this!  Unless you feel it's sufficient without that.  Otherwise I'll get on it eventually!

**Comment by tekktrik** [comment]
Just tested, works like you'd expect!  Tested using Raspberry Pi 2 Zero W with Blinka, a Circuit Playground Bluefruit at CircuitPython 7.1.0, and my Adafruit IO account.  Picture for confirmation!

![sound_level_confirmed](https://user-images.githubusercontent.com/89490472/149545982-bfcace31-db73-4e47-8ff4-1677f0486686.PNG)

**Comment by tannewt** [comment]
:tada:
