### ISSUE TITLE
Does not work on macOS due to missing adapter address

### ISSUE THREAD

**Issue by alexwhittemore** [adafruit/Adafruit_CircuitPython_BLE_BroadcastNet#14]
(Backstory: I'm mostly developing on a RasPi 4 or a Bluefruit Sense, but I'm also trying to do comparisons against code running on Mac, as here)

Merely trying to import broadcastnet fails on the macOS platform even though adafruit_blinka_bleio supports mac, on the basis that the adapter never gets an address on mac (Python 3.7.9):
```
>>> import adafruit_ble_broadcastnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<....>/adafruit_ble_broadcastnet.py", line 67, in <module>
    _ble._adapter.address.address_bytes  # pylint: disable=protected-access
AttributeError: 'NoneType' object has no attribute 'address_bytes'
```
Relevant line in _bleio is 145 of https://github.com/adafruit/Adafruit_Blinka_bleio/blob/master/_bleio/adapter_.py: if it's not linux, an adapter just never gets an address.

I'm thinking this isn't actually necessary for bridge usage anyway? I'm going to try working around it and maybe submit a PR. I'm also open to being told it's foolish and underlying bleak support is insufficient on macos for other reasons.

**Comment by dhalbert** [comment]
I was thinking of generating a fake address by hashing the UUID representing the device down to a 48-bit "address".

**Comment by alexwhittemore** [comment]
That certainly sounds less dumb than my current "000000000000" strategy.

Blindly setting the address to all zeros does at least fix the problem of broadcastnet assuming the address exists at all. I can't say whether there are any other issues that pop up yet, since I haven't been able to get it working (the bridge) on either macOS here, or RasPi (which is why I resorted to this in the first place). I can verify with a generic advertisement scan `for measurement in ble.start_scan():` instead of `for measurement in ble.start_scan(adafruit_ble_broadcastnet.AdafruitSensorMeasurement):` that ads ARE heard by either mac or RasPi. But for some reason they're not getting recognized correctly as `AdafruitSensorMeasurement`s on either.
