### ISSUE TITLE
AdafruitSensorMeasurement does not allow a sequence number of 0 in constructor

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_BLE_BroadcastNet#8]
The constructor for `AdafruitSensorMeasurement` conditionally sets sequence_number based on testing the variable, `0` will evaluate to `False` causing no setting of the sequence_number.

https://github.com/adafruit/Adafruit_CircuitPython_BLE_BroadcastNet/blob/81aee22c68e1c5ea3ae35e70b50a4f3ae0419d49/adafruit_ble_broadcastnet.py#L156-L157

Perhaps this was intended to be `is not None`?

The `broadcast` function in the same file does not use the construtor's arguments to set the `sequence_number`.

This is just from inspection, I've not executed the code...

**Comment by tannewt** [comment]
Fixed by #19
